---
- hosts: all
  connection: local
  sudo: yes
  vars_files:
    - /vagrant/vars/config.yml

  roles:
    - socks
    - tinyproxy
    - { role: openconnect, vpn_url: "{{ server }}", vpn_user: "{{ user }}", vpn_password: "{{ password }}", vpn_group: "{{ group }}" }
#    - { role: openvpn, config_directory: "{{ ovpn.directory }}", vpn_config: "{{ ovpn.configuration }}" }
