---
# tasks file for tinyproxy

- name: Install Tinyproxy
  apt: update_cache=true name=tinyproxy

- name: Configure Tinyproxy
  template: dest=/etc/tinyproxy.conf src=tinyproxy.conf.j2
  notify:
    - restart tinyproxy

- name: Configure Tinyproxy cron restart
  template: dest=/etc/cron.hourly/tinyproxy.sh src=tinyproxy.sh.j2 mode="u+rx"